import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "@/app/globals.css";
import { Header } from "@/components/shared";

const font = Chakra_Petch({
	// subsets: ["cyrillic"],
	variable: "--font-chakra_petch",
	weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Next Wheels | UIXER",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${font.variable} antialiased min-h-screen`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
