import type { Metadata } from "next";
import { Header } from "@/shared/components/shared";
import { font } from "../layout";

export const metadata: Metadata = {
	title: "Next Wheels | UIXER",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<main className={`${font.variable} antialiased min-h-screen`}>
			<Header />
			{children}
			{modal}
		</main>
	);
}
