import type { Metadata } from "next";
import { font } from "../layout";

export const metadata: Metadata = {
	title: "Next Wheels | UIXER",
	description: "Generated by create next app",
};

export default function DashboardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${font.variable} antialiased min-h-screen`}>
				{children}
			</body>
		</html>
	);
}
