import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Container, Header } from "@/components/shared";

const nunito = Nunito({
	// subsets: ["cyrillic"],
	variable: "--font-nunito",
	weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Next Pizza | UIXER",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${nunito.variable} antialiased min-h-screen`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
